### ISSUE TITLE
How to produce correct polygons from a bitmap mask?

### ISSUE THREAD

**Issue by callzhang** [mattijn/topojson#119]
I have used cv2 to produce polygongs from a mask. The problem is, the points has a gap of 1 px between polygons. Therefore the produced polygons are not "close" to each other. Shall I improve the path-find algorithm to have the polygons to share points, or to use some quantization algorithm to fix this issue?

Code to produce the polygon:
```
mask = self.array.astype(np.uint8)
mask = cv2.copyMakeBorder(mask, 1, 1, 1, 1, cv2.BORDER_CONSTANT, value=0)
polygons = cv2.findContours(mask, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE, offset=(-1, -1))
polygons = polygons[0] if len(polygons) == 2 else polygons[1]
polygons = [polygon.flatten() for polygon in polygons]
```
(referenced from `imantics` package)

Before simplify:
![image](https://user-images.githubusercontent.com/5102827/110661906-f8751b80-81ff-11eb-87e3-91b1d545c015.png)

After simplify:
![image](https://user-images.githubusercontent.com/5102827/110662118-2a867d80-8200-11eb-96a5-7f5fb3c767d7.png)

**Comment by mattijn** [comment]
Thanks for raising this issue. My apologies for not replier sooner. I'm not sure why I havent seen this issue before.

Your problem is interesting and I have no idea if `topojson` can be of value here. I tried a few things, but I didn't get as close as your result, so probably you got already further than I did.

Anyway what I tried is using the `prequantize` and `presimplify` options, while setting `topology` to False, since you are merely aiming for a combination of simplification and quantization, I think.

This is what I tried

```python
import cv2
import numpy as np
from collections import defaultdict
from shapely.geometry import MultiPolygon, Polygon
from matplotlib import pyplot as plt
import topojson as tp

# function from here: https://michhar.github.io/masks_to_polygons_and_back/
def mask_to_polygons(mask, min_area=10.):
    """Convert a mask ndarray (binarized image) to Multipolygons"""
    # first, find contours with cv2: it's much faster than shapely
    contours, hierarchy = cv2.findContours(mask,
                                  cv2.RETR_CCOMP,
                                  cv2.CHAIN_APPROX_NONE)
    if not contours:
        return MultiPolygon()
    # now messy stuff to associate parent and child contours
    cnt_children = defaultdict(list)
    child_contours = set()
    assert hierarchy.shape[0] == 1
    # http://docs.opencv.org/3.1.0/d9/d8b/tutorial_py_contours_hierarchy.html
    for idx, (_, _, _, parent_idx) in enumerate(hierarchy[0]):
        if parent_idx != -1:
            child_contours.add(idx)
            cnt_children[parent_idx].append(contours[idx])
    # create actual polygons filtering by area (removes artifacts)
    all_polygons = []
    for idx, cnt in enumerate(contours):
        if idx not in child_contours and cv2.contourArea(cnt) >= min_area:
            assert cnt.shape[1] == 1
            poly = Polygon(
                shell=cnt[:, 0, :],
                holes=[c[:, 0, :] for c in cnt_children.get(idx, [])
                       if cv2.contourArea(c) >= min_area])
            all_polygons.append(poly)
    all_polygons = MultiPolygon(all_polygons)

    return all_polygons
```
```python
img = cv2.imread(r'/Users/mattijnvanhoek/Downloads/110661906-f8751b80-81ff-11eb-87e3-91b1d545c015.png', cv2.IMREAD_UNCHANGED)
plt.imshow(img)
```
![Unknown-4](https://user-images.githubusercontent.com/5186265/115160813-89120780-a09a-11eb-826e-397dbc8b960f.png)
```python
edges = cv2.Canny(img, 1, 1)
plt.imshow(edges, cmap='gray', interpolation='bicubic')
```
![Unknown-5](https://user-images.githubusercontent.com/5186265/115160827-96c78d00-a09a-11eb-8c91-baac4482ce89.png)
```python
poly = mask_to_polygons(edges, min_area=1)
poly # seems to be reversed, but not important now
```
![Image 18-04-2021 at 23 09](https://user-images.githubusercontent.com/5186265/115160946-2836ff00-a09b-11eb-8237-200e0c8d3877.jpg)
```python
# low prequantize values only work with the topojson from the unreleased master branch on github
# !python -m pip uninstall topojson --yes
# !python -m pip install git+https://github.com/mattijn/topojson.git --upgrade
tp.Topology(poly, prequantize=False, presimplify=200, topology=False).to_alt()
```
![Image 18-04-2021 at 23 03](https://user-images.githubusercontent.com/5186265/115160875-c4143b00-a09a-11eb-83ef-5e35221db223.jpg)

```python
tp.Topology(poly, prequantize=50, presimplify=False, topology=False).to_alt()
```
![Image 18-04-2021 at 23 04](https://user-images.githubusercontent.com/5186265/115160889-d1312a00-a09a-11eb-9d57-8b7af235be66.jpg)

**Comment by callzhang** [comment]
Hi Matt, sorry for my late reply. I have tried different options and couldn't "merge" the neighbouring points (from difference polygons) together. So I just loop through all the points and manually merged the points together. 
My use case is convert a bitmap mask (from semantic segmentation result from a deep learning model) to vectorized results. Maybe it's a good feature for you to add. Let me know if here is anything I can contribute.
