### ISSUE TITLE
holes in multipolygons are lost by simplification

### ISSUE THREAD

**Issue by mephinet** [mattijn/topojson#167]
I'm experiencing an issue when simplifying a geometry that has a hole in it (and is thus a Multipolygon) in the input).
This reproducer downloads a Geopackage, extracts a single Multipolygon, and then uses topojson to simplify it. 
It saves a GEOJSON before and after simplifying. You can see that while the original GeoJSON still has a hole, the simplified one does not any more:
https://github.com/mephinet/topojson-reproducer
My first guess is that the nesting level in the "coordinates" confuses topojson..?

**Comment by mattijn** [comment]
Thanks for reporting. This is the same issue as is described here: https://github.com/mattijn/topojson/issues/148#issuecomment-1137924855. It is not because of the simplification. Another attempt to see if understand why this occurs:

```python
from shapely import geometry
import topojson as tp
import json

mp_in = geometry.shape({
    "type": "MultiPolygon",
    "coordinates": [
        [
            [[0, 0], [20, 0], [10, 20], [0, 0]],  # CCW
            [[3, 2], [10, 16], [17, 2], [3, 2]],  # CW
        ]
    ]
})


# exterior ring is counter-clockwise
# interior ring is clockwise (not counter-clockwise)
assert (mp_in[0].exterior.is_ccw, 
        mp_in[0].interiors[0].is_ccw) == (True, False)
mp_in
```

> <img width="108" alt="image" src="https://user-images.githubusercontent.com/5186265/184441806-e3214b37-7025-4e88-a537-5b6ea2b6e298.png">

```python
mp_in.wkt
```

> ```cmd
> 'MULTIPOLYGON (((0 0, 20 0, 10 20, 0 0), (3 2, 10 16, 17 2, 3 2)))'
> ```

```python
topo = tp.Topology(mp_in, prequantize=False)
geom = json.loads(topo.to_geojson())['features'][0]['geometry']
mp_out = geometry.shape(geom)
mp_out
```

> <img width="108" alt="image" src="https://user-images.githubusercontent.com/5186265/184442038-080a4437-53e0-435f-ab21-062c2ec9b36a.png">

```python
mp_out.wkt
```

> ```cmd
> 'MULTIPOLYGON (((0 0, 20 0, 10 20, 0 0)), ((3 2, 17 2, 10 16, 3 2)))'
> ```

Comparison in and out: 
```cmd
mp_in  == 'MULTIPOLYGON (((0 0, 20 0, 10 20, 0 0), (3 2, 10 16, 17 2, 3 2)))'
mp_out == 'MULTIPOLYGON (((0 0, 20 0, 10 20, 0 0)), ((3 2, 17 2, 10 16, 3 2)))'
```
The exterior ring and interior ring has become two separate polygons within the multipolygon. That is invalid.
Check the computiontion of the Dedup [phase](https://mattijn.github.io/topojson/how-it-works.html#dedup) and the subsequent Hashmap [phase](https://mattijn.github.io/topojson/how-it-works.html#hashmap).

```python
from topojson.core.dedup import Dedup
from topojson.core.hashmap import Hashmap

Dedup(mp_in)
```

```cmd
Dedup(
{'bbox': (0.0, 0.0, 20.0, 20.0),
 'bookkeeping_arcs': [[0], [1]],
 'bookkeeping_coords': [],
 'bookkeeping_duplicates': [],
 'bookkeeping_geoms': [[0, 1]],
 'bookkeeping_shared_arcs': [],
 'coordinates': [],
 'junctions': [<shapely.geometry.point.Point object at 0x7fb5a99d2bb0>,
               <shapely.geometry.point.Point object at 0x7fb5a99d2ca0>],
 'linestrings': [array([[ 0.,  0.],
       [20.,  0.],
       [10., 20.],
       [ 0.,  0.]]),
                 array([[ 3.,  2.],
       [10., 16.],
       [17.,  2.],
       [ 3.,  2.]])],
 'objects': {0: {'arcs': [0], 'type': 'MultiPolygon'}},
 'type': 'Topology'}
)
```

```python
Hashmap(mp_in)
```

```cmd
Hashmap(
{'bbox': (0.0, 0.0, 20.0, 20.0),
 'coordinates': [],
 'linestrings': [array([[ 0.,  0.],
       [20.,  0.],
       [10., 20.],
       [ 0.,  0.]]),
                 array([[ 3.,  2.],
       [10., 16.],
       [17.,  2.],
       [ 3.,  2.]])],
 'objects': {'data': {'geometries': [{'arcs': [[[0]], [[1]]],
                                      'id': 0,
                                      'type': 'MultiPolygon'}],
                      'type': 'GeometryCollection'}},
 'type': 'Topology'}
)
```

I think there should be a check in creating the `Hashmap` object, where the `bookkeeping_arcs` (`[[0], [1]]`) of the `Dedup` object is used to serialize this into an updated `arcs` object (becomes `'arcs': [[[0]], [[1]]]`). 
If the item has `len` 1, than it should not stay nested. 

Note: with 2 unique holes this also will work fine, since the `bookkeeping_arcs` then becomes `[[0], [1], [2]]`. Check:

```python
mp_in = geometry.shape({
    "type": "MultiPolygon",
    "coordinates": [
        [
            [[0, 0], [20, 0], [10, 20], [0, 0]],  # CCW
            [[11, 2], [14, 7], [17, 2], [11, 2]],  # CW
            [[3, 2], [6, 7], [9, 2], [3, 2]],  # CW            
        ]
    ]
})
```

Probably should be solved around here:  https://github.com/mattijn/topojson/blob/master/topojson/core/hashmap.py#L327:L335. Not sure if

**Comment by mattijn** [comment]
This issue is fixed by PR #168 🥳.
Result will become:
<img src="https://user-images.githubusercontent.com/5186265/184510041-a3c65397-0f3c-4109-83a6-8a0175db06e9.png" width="200">

**Comment by mephinet** [comment]
I tested the master, and the issue is resolved. Thanks, @mattijn, this is really awesome!

**Comment by mephinet** [comment]
Tested again with release 1.5, can confirm this is fixed. Thanks a lot, @mattijn !
