### ISSUE TITLE
Deprecation warning for shapely 2.0

### ISSUE THREAD

**Issue by theroggy** [mattijn/topojson#170]
A new deprecation warning popped up recently:
```
envs\orthosegdev\lib\site-packages\topojson\core\cut.py:112: ShapelyDeprecationWarning: STRtree 
will be changed in 2.0.0 and will not be compatible with versions < 2.
  tree_splitter = STRtree(mp) 
```

Just a heads up, not sure what the impact is...

**Comment by mattijn** [comment]
Thanks for raising. It took me a while to figure out, but in shapely `1.8.0` the functions `.query_geoms()` and `.query_items()` were introduced for the `strtree`. I've updated topojson to include these functions, but in shapely `1.8.3` these functions were removed again. 
So:
- shapely version < `1.8.0`: the `strtree.query()` returns geometries.
- `1.8.0` <= shapely version < `1.8.3`, the `strtree.query_geoms()` returns geometries and `tree.query_items()` returns indices.
- shapely version >= `1.8.3` (inc `2.0a1`) the `strtree.query()` returns indices.

I updated to 2.0a1, but then I received the error:
```python
AttributeError: 'numpy.int64' object has no attribute 'coords'
```
And that is because of this part in the code:

https://github.com/mattijn/topojson/blob/master/topojson/ops.py#L102-L106

Here you can see:
```python
try:
    pts_within_bbox = tree_splitter.query_geoms(line)
except AttributeError:
    # catch < v1.8 behavior of shapely
    pts_within_bbox = tree_splitter.query(line)
```

The `.query_geoms` function is removed, and so it fallback to the `.query` function, but this function now returns indices instead of geometries and therefor _a few lines later_ the error arise.
```python
pts_xy_bbox = np.array([x for pt in pts_within_bbox for x in pt.coords])
```
Since it tries to acces the `.coords`, which is hard of an index integer.

Apparently I can do from shapely version > `1.8.3`:
```
ind_within_bbox = tree_splitter.query(line)
pts_within_bbox = tree_splitter.geometries.take(ind_within_bbox)
```
The file topojson/ops.py still contain one referral to `query_items` and one to `query_geoms`.
https://github.com/mattijn/topojson/blob/9aad0a7989142a077fd7fca07c691b6a925d9b4a/topojson/ops.py

**Comment by mattijn** [comment]
So how to find out if the `strtree.query()` returns indices or geometries?
```python
from shapely.geometry import Point
from shapely.strtree import STRtree
tree = STRtree([Point(i, i) for i in range(10)])

if hasattr(tree, 'geometries'):
    # shapely version >= 1.8.3
    index = tree.query(geom)
    geom_tree = tree.geometries.take(index)
elif hasattr(tree, 'query_geoms'):
    # 1.8.0 <= shapely version < 1.8.3
    geom_tree = tree.query_geoms(geom)
else:
    # shapely version < 1.8.0
    geom_tree = tree.query(geom)
```

**Comment by MichaelCurrie** [comment]
For anyone else around the world landing on this issue as I did, the solution is simply to upgrade shapely past version 2.0.0.  You can do this via:

```
pip install --upgrade shapely
```
