### ISSUE TITLE
Dependencies are not defined for PyPI package

### ISSUE THREAD

**Issue by kannes** [mattijn/topojson#18]
`pip install topojson` left me with

```
>>> import topojson
ModuleNotFoundError: No module named 'simplification'
```

Please make sure that dependencies are properly defined that so that Pip will resolve them when installing.

**Comment by mattijn** [comment]
I already changed from `requirements.txt` (which indeed did not include `simplification`) to a `pyproject.toml` file in https://github.com/mattijn/topojson/commit/71b9acd8359d9044806589c767d66dfabc2d31a1. In this `toml` file I did include all required dependencies. So this should be fixed with the next release.
